name: secure-kafka

volumes:
  kafka-1-data:
  kafka-2-data:
  kafka-3-data:

networks:
  net:

services:

  kafka-1:
    image: confluentinc/cp-kafka:7.4.10
    hostname: kafka-1
    container_name: secure-kafka_kafka-1
    ports:
      - 127.0.0.1:19094:9094
    volumes:
    - kafka-1-data:/var/lib/kafka/data
    - ./admin-client.properties:/etc/kafka/admin-client.properties
    - ./kafka_server_jaas.conf:/etc/kafka/secrets/kafka_server_jaas.conf
    - ./certs/kafka.truststore.jks:/etc/kafka/secrets/kafka.truststore.jks:ro
    - ./certs/kafka-1.keystore.jks:/etc/kafka/secrets/kafka.keystore.jks:ro
    networks:
      - net
    environment:
      CLUSTER_ID: u0l1UvzmTeiKYi321oE81A
      KAFKA_NODE_ID: 1
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:9092,EXTERNAL://127.0.0.1:19094
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:SASL_SSL,CONTROLLER:SASL_SSL,EXTERNAL:SASL_SSL
      KAFKA_OPTS: '-Djava.security.auth.login.config=/etc/kafka/secrets/kafka_server_jaas.conf'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
      # ACL
      KAFKA_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: false
      KAFKA_SUPER_USERS: User:admin
      # SASL
      KAFKA_SECURITY_PROTOCOL: SASL_SSL
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN
      # SSL
      KAFKA_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/kafka.keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: 123456
      KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka.truststore.jks
      KAFKA_SSL_TRUSTSTORE_PASSWORD: 123456
      KAFKA_SSL_CLIENT_AUTH: required
    healthcheck:
      test: kafka-cluster cluster-id -c /etc/kafka/admin-client.properties -b localhost:9092 || exit 1
      interval: 1s
      timeout: 5s
      retries: 60

  kafka-2:
    image: confluentinc/cp-kafka:7.4.10
    hostname: kafka-2
    container_name: secure-kafka_kafka-2
    ports:
      - 127.0.0.1:29094:9094
    volumes:
    - kafka-2-data:/var/lib/kafka/data
    - ./admin-client.properties:/etc/kafka/admin-client.properties
    - ./kafka_server_jaas.conf:/etc/kafka/secrets/kafka_server_jaas.conf
    - ./certs/kafka.truststore.jks:/etc/kafka/secrets/kafka.truststore.jks:ro
    - ./certs/kafka-2.keystore.jks:/etc/kafka/secrets/kafka.keystore.jks:ro
    networks:
      - net
    environment:
      CLUSTER_ID: u0l1UvzmTeiKYi321oE81A
      KAFKA_NODE_ID: 2
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-2:9092,EXTERNAL://127.0.0.1:29094
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:SASL_SSL,CONTROLLER:SASL_SSL,EXTERNAL:SASL_SSL
      KAFKA_OPTS: '-Djava.security.auth.login.config=/etc/kafka/secrets/kafka_server_jaas.conf'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
      # ACL
      KAFKA_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: false
      KAFKA_SUPER_USERS: User:admin
      # SASL
      KAFKA_SECURITY_PROTOCOL: SASL_SSL
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN
      # SSL
      KAFKA_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/kafka.keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: 123456
      KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka.truststore.jks
      KAFKA_SSL_TRUSTSTORE_PASSWORD: 123456
      KAFKA_SSL_CLIENT_AUTH: required
    healthcheck:
      test: kafka-cluster cluster-id -c /etc/kafka/admin-client.properties -b localhost:9092 || exit 1
      interval: 1s
      timeout: 5s
      retries: 60
  
  kafka-3:
    image: confluentinc/cp-kafka:7.4.10
    hostname: kafka-3
    container_name: secure-kafka_kafka-3
    ports:
      - 127.0.0.1:39094:9094
    volumes:
    - kafka-3-data:/var/lib/kafka/data
    - ./admin-client.properties:/etc/kafka/admin-client.properties
    - ./kafka_server_jaas.conf:/etc/kafka/secrets/kafka_server_jaas.conf
    - ./certs/kafka.truststore.jks:/etc/kafka/secrets/kafka.truststore.jks:ro
    - ./certs/kafka-3.keystore.jks:/etc/kafka/secrets/kafka.keystore.jks:ro
    networks:
      - net
    environment:
      CLUSTER_ID: u0l1UvzmTeiKYi321oE81A
      KAFKA_NODE_ID: 3
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-3:9092,EXTERNAL://127.0.0.1:39094
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:SASL_SSL,CONTROLLER:SASL_SSL,EXTERNAL:SASL_SSL
      KAFKA_OPTS: '-Djava.security.auth.login.config=/etc/kafka/secrets/kafka_server_jaas.conf'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
      # ACL
      KAFKA_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: false
      KAFKA_SUPER_USERS: User:admin
      # SASL
      KAFKA_SECURITY_PROTOCOL: SASL_SSL
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN
      # SSL
      KAFKA_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/kafka.keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: 123456
      KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka.truststore.jks
      KAFKA_SSL_TRUSTSTORE_PASSWORD: 123456
      KAFKA_SSL_CLIENT_AUTH: required
    healthcheck:
      test: kafka-cluster cluster-id -c /etc/kafka/admin-client.properties -b localhost:9092 || exit 1
      interval: 1s
      timeout: 5s
      retries: 60
  
  ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: secure-kafka_ui
    hostname: kafka-ui
    ports:
      - 127.0.0.1:8080:8080
    networks:
      - net
    environment:
      KAFKA_CLUSTERS_0_NAME: cluster_1
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_SSL
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: PLAIN
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin";'
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_LOCATION: /kafka.keystore.jks
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_PASSWORD: 123456
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:9092,kafka-2:9092,kafka-3:9092
      KAFKA_CLUSTERS_0_SSL_TRUSTSTORELOCATION: /kafka.truststore.jks
      KAFKA_CLUSTERS_0_SSL_TRUSTSTOREPASSWORD: 123456
    volumes:
    - ./certs/kafka.truststore.jks:/kafka.truststore.jks:ro
    - ./certs/kafka-ui.keystore.jks:/kafka.keystore.jks:ro
    depends_on:
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy
